services:
  - type: web
    name: gps-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sensor.py"
    envVars:
      - key: PORT
        value: 5000
